version: '3.8'

services:
  app:
    container_name: richscope-coming-soon
    build: .
    ports:
      - '5000:80'
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      APP_ENV: production

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
